In [52]:
import pandas as pd
# File paths for the provided data
non_polarized_data_path = 'abm_milk_choice_upload experimentNonPolarizedNew-table .csv'
polarized_data_path = 'PolarizedNew-table.csv'
# Load the dataframes
polarized_df = pd.read_csv(polarized_data_path, skiprows=6, sep=",")
non_polarized_df = pd.read_csv(non_polarized_data_path, skiprows=6, sep=",")
non_polarized_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73600 entries, 0 to 73599
Data columns (total 29 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   [run number]                         73600 non-null  int64
 1   habit-threshold                      73600 non-null  int64
 2   p-interact                           73600 non-null  float64
 3   incumbent-initial-habit              73600 non-null  int64
 4   cognitive-dissonance-threshold       73600 non-null  float64
 5   social-conformity                    73600 non-null  float64
 6   social-susceptibility                73600 non-null  float64
 7   memory-lifetime                      73600 non-null  int64
 8   justification                        73600 non-null  float64
 9   network-parameter                    73600 non-null  int64
 10  social-blindness                     73600 non-null  float64
 11  oat-health-mean-initial              73600 non-null  int64
 12  oat-env-mean-initial                 73600 non-null  int64
 13  soy-health-mean-initial              73600 non-null  int64
 14  soy-env-mean-initial                 73600 non-null  int64
 15  almond-health-mean-initial           73600 non-null  int64
 16  almond-env-mean-initial              73600 non-null  int64
 17  [step]                               73600 non-null  int64
 18  count turtles with [color = red]     73600 non-null  int64
 19  count turtles with [color = green]   73600 non-null  int64
 20  count turtles with [color = white]   73600 non-null  int64
 21  count turtles with [color = yellow]  73600 non-null  int64
 22  mean-health-impact                   73600 non-null  float64
 23  mean-env-impact                      73600 non-null  float64
 24  total-milk                           73600 non-null  float64
 25  mean-incum                           73600 non-null  float64
 26  mean-oat                             73600 non-null  float64
 27  mean-almond                          73600 non-null  float64
 28  mean-soy                             73600 non-null  float64
dtypes: float64(13), int64(16)
memory usage: 16.3 MB

In [39]:
polarized_df.head()

,[run number],habit-threshold,p-interact,incumbent-initial-habit,cognitive-dissonance-threshold,social-conformity,social-susceptibility,memory-lifetime,justification,network-parameter,...,count turtles with [color = green],count turtles with [color = white],count turtles with [color = yellow],mean-health-impact,mean-env-impact,total-milk,mean-incum,mean-oat,mean-almond,mean-soy
0,1,4,0.7,1,0.1,-0.9,0.7,5,0.9,2,...,0,0,0,29.650000,6.558000,2300000.0,2000.000000,100.000000,100.000000,100.000000
1,1,4,0.7,1,0.1,-0.9,0.7,5,0.9,2,...,10,21,3,42.994181,1299.020437,4616204.5,2000.000000,100.000000,100.000000,100.000000
2,3,4,0.7,1,0.1,-0.9,0.7,5,0.9,2,...,0,0,0,29.650000,6.558000,2300000.0,2000.000000,100.000000,100.000000,100.000000
3,6,4,0.7,1,0.1,-0.9,0.7,5,0.9,2,...,0,0,0,29.650000,6.558000,2300000.0,2000.000000,100.000000,100.000000,100.000000
4,1,4,0.7,1,0.1,-0.9,0.7,5,0.9,2,...,57,75,68,39.004911,1164.672726,7022998.2,1637.852231,255.365676,256.697564,256.878229

## for polarized data

In [40]:
grouped_polarized_df = polarized_df.groupby(["[run number]", "[step]"]).mean().reset_index()

In [58]:
grouped_polarized_df

,[run number],[step],habit-threshold,p-interact,incumbent-initial-habit,cognitive-dissonance-threshold,social-conformity,social-susceptibility,memory-lifetime,justification,...,count turtles with [color = green],count turtles with [color = white],count turtles with [color = yellow],mean-health-impact,mean-env-impact,total-milk,mean-incum,mean-oat,mean-almond,mean-soy
0,1,0,4.0,0.7,1.0,0.1,-0.9,0.7,5.0,0.9,...,0.0,0.0,0.0,29.650000,6.558000,2300000.00,2000.000000,100.000000,100.000000,100.000000
1,1,1,4.0,0.7,1.0,0.1,-0.9,0.7,5.0,0.9,...,10.0,21.0,3.0,42.994181,1299.020437,4616204.50,2000.000000,100.000000,100.000000,100.000000
2,1,2,4.0,0.7,1.0,0.1,-0.9,0.7,5.0,0.9,...,57.0,75.0,68.0,39.004911,1164.672726,7022998.20,1637.852231,255.365676,256.697564,256.878229
3,1,3,4.0,0.7,1.0,0.1,-0.9,0.7,5.0,0.9,...,96.0,95.0,104.0,36.870480,1093.233717,9463249.00,1481.949942,318.807906,319.383295,320.109658
4,1,4,4.0,0.7,1.0,0.1,-0.9,0.7,5.0,0.9,...,112.0,120.0,128.0,35.038566,1033.902753,11884755.71,1366.998105,351.098808,350.794520,352.615277
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73595,1600,41,4.0,0.9,3.0,0.3,-0.5,0.9,5.0,0.9,...,216.0,138.0,232.0,17.832886,503.324412,84545462.09,543.811758,355.938685,340.300505,358.636352
73596,1600,42,4.0,0.9,3.0,0.3,-0.5,0.9,5.0,0.9,...,232.0,138.0,237.0,17.444557,492.294692,86111554.18,531.053823,350.184759,334.009178,350.844330
73597,1600,43,4.0,0.9,3.0,0.3,-0.5,0.9,5.0,0.9,...,211.0,134.0,232.0,17.246549,486.865091,87658607.70,525.646811,344.995056,329.754749,346.656904
73598,1600,44,4.0,0.9,3.0,0.3,-0.5,0.9,5.0,0.9,...,209.0,156.0,226.0,16.967086,478.165411,89191609.41,512.455169,344.852490,329.099670,346.594381
73599,1600,45,4.0,0.9,3.0,0.3,-0.5,0.9,5.0,0.9,...,213.0,131.0,258.0,16.509359,464.597831,90687404.89,496.554439,338.047442,321.465645,339.727954

In [53]:
# List of file names to process
file_names = [
    "abm_milk_choice_upload experimentNonPolarizedNew-table .csv", "PolarizedNew-table.csv"
]

# Initialize an empty list to store cleaned dataframes
cleaned_dfs = []

# Process each file
for file in file_names:
    # Read the dataset, skipping the first 6 rows
    df = pd.read_csv(file, skiprows=6, sep=",")  # Ensure correct delimiter (adjust to actual file format)
    
    # Check if the dataset was misread as a single column
    if len(df.columns) == 1:
        # Re-read using a different delimiter if necessary
        df = pd.read_csv(file, skiprows=6, sep="\t")
    
    # Standardize column names by stripping whitespace
    df.columns = df.columns.str.strip()
    
    # Append to the cleaned dataframes list
    cleaned_dfs.append(df)

# Align columns by filling missing columns in each dataset with NaN
all_columns = set().union(*[df.columns for df in cleaned_dfs])
aligned_dfs = [df.reindex(columns=all_columns) for df in cleaned_dfs]

# Concatenate all aligned dataframes into one long dataframe
merged_data = pd.concat(aligned_dfs, axis=0, ignore_index=True)

# Display the structure of the merged dataset
print(merged_data.info())
merged_data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147200 entries, 0 to 147199
Data columns (total 29 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   soy-health-mean-initial              147200 non-null  int64
 1   social-blindness                     147200 non-null  float64
 2   count turtles with [color = white]   147200 non-null  int64
 3   justification                        147200 non-null  float64
 4   count turtles with [color = red]     147200 non-null  int64
 5   almond-env-mean-initial              147200 non-null  int64
 6   mean-oat                             147200 non-null  float64
 7   mean-incum                           147200 non-null  float64
 8   [run number]                         147200 non-null  int64
 9   oat-env-mean-initial                 147200 non-null  int64
 10  mean-soy                             147200 non-null  float64
 11  cognitive-dissonance-threshold       147200 non-null  float64
 12  social-conformity                    147200 non-null  float64
 13  count turtles with [color = yellow]  147200 non-null  int64
 14  mean-almond                          147200 non-null  float64
 15  oat-health-mean-initial              147200 non-null  int64
 16  incumbent-initial-habit              147200 non-null  int64
 17  habit-threshold                      147200 non-null  int64
 18  p-interact                           147200 non-null  float64
 19  count turtles with [color = green]   147200 non-null  int64
 20  almond-health-mean-initial           147200 non-null  int64
 21  mean-env-impact                      147200 non-null  float64
 22  social-susceptibility                147200 non-null  float64
 23  total-milk                           147200 non-null  float64
 24  network-parameter                    147200 non-null  int64
 25  [step]                               147200 non-null  int64
 26  memory-lifetime                      147200 non-null  int64
 27  mean-health-impact                   147200 non-null  float64
 28  soy-env-mean-initial                 147200 non-null  int64
dtypes: float64(13), int64(16)
memory usage: 32.6 MB
None

,soy-health-mean-initial,social-blindness,count turtles with [color = white],justification,count turtles with [color = red],almond-env-mean-initial,mean-oat,mean-incum,[run number],oat-env-mean-initial,...,count turtles with [color = green],almond-health-mean-initial,mean-env-impact,social-susceptibility,total-milk,network-parameter,[step],memory-lifetime,mean-health-impact,soy-env-mean-initial
0,1,0.2,0,0.9,1000,1,100.0,2000.0,2,1,...,0,1,6.558000,0.1,2300000.0,2,0,5,29.65000,1
1,1,0.6,0,0.9,1000,1,100.0,2000.0,6,1,...,0,1,6.558000,0.1,2300000.0,2,0,5,29.65000,1
2,1,0.3,0,0.9,1000,1,100.0,2000.0,3,1,...,0,1,6.558000,0.1,2300000.0,2,0,5,29.65000,1
3,1,0.6,9,0.9,964,1,100.0,2000.0,6,1,...,14,1,1299.946183,0.1,4615484.3,2,1,5,43.03127,1
4,1,0.2,10,0.9,974,1,100.0,2000.0,2,1,...,8,1,1303.662960,0.1,4613323.7,2,1,5,43.13927,1

In [56]:
grouped_data = merged_data.groupby(["[run number]", "[step]"]).mean().reset_index()

In [57]:
grouped_data

,[run number],[step],soy-health-mean-initial,social-blindness,count turtles with [color = white],justification,count turtles with [color = red],almond-env-mean-initial,mean-oat,mean-incum,...,p-interact,count turtles with [color = green],almond-health-mean-initial,mean-env-impact,social-susceptibility,total-milk,network-parameter,memory-lifetime,mean-health-impact,soy-env-mean-initial
0,1,0,1.0,0.1,0.0,0.9,1000.0,1.0,100.000000,2000.000000,...,0.4,0.0,1.0,6.558000,0.4,2.300000e+06,2.0,5.0,29.650000,1.0
1,1,1,1.0,0.1,17.0,0.9,968.5,1.0,100.000000,2000.000000,...,0.4,10.0,1.0,1301.321342,0.4,4.614764e+06,2.0,5.0,43.066884,1.0
2,1,2,1.0,0.1,57.0,0.9,856.5,1.0,210.796391,1741.935446,...,0.4,41.5,1.0,1210.977080,0.4,6.990778e+06,2.0,5.0,40.382489,1.0
3,1,3,1.0,0.1,71.5,0.9,773.0,1.0,270.594508,1596.954157,...,0.4,75.0,1.0,1144.718579,0.4,9.399847e+06,2.0,5.0,38.411808,1.0
4,1,4,1.0,0.1,94.0,0.9,703.0,1.0,309.000644,1474.907988,...,0.4,94.0,1.0,1083.831399,0.4,1.180146e+07,2.0,5.0,36.536733,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73595,1600,41,1.0,1.0,147.0,0.9,419.0,1.0,351.076573,550.132445,...,0.6,216.5,1.0,505.911459,0.6,8.443972e+07,10.0,5.0,17.876285,1.0
73596,1600,42,1.0,1.0,150.0,0.9,405.0,1.0,343.620730,535.372884,...,0.6,215.0,1.0,493.387418,0.6,8.599569e+07,10.0,5.0,17.435894,1.0
73597,1600,43,1.0,1.0,145.0,0.9,422.0,1.0,340.663923,525.148396,...,0.6,214.5,1.0,485.313559,0.6,8.753120e+07,10.0,5.0,17.160083,1.0
73598,1600,44,1.0,1.0,160.5,0.9,408.5,1.0,339.385277,514.199604,...,0.6,203.5,1.0,477.991546,0.6,8.905408e+07,10.0,5.0,16.920255,1.0
73599,1600,45,1.0,1.0,144.0,0.9,405.5,1.0,333.150751,497.419155,...,0.6,219.5,1.0,463.778180,0.6,9.053810e+07,10.0,5.0,16.439889,1.0

In [60]:
# 替换列名中的连字符
grouped_data.columns = grouped_data.columns.str.replace("-", "_")
# 确保你的变量名符合 Python 和 patsy 的要求
print(grouped_data.columns)

Index(['[run number]', '[step]', 'soy_health_mean_initial', 'social_blindness',
       'count turtles with [color = white]', 'justification',
       'count turtles with [color = red]', 'almond_env_mean_initial',
       'mean_oat', 'mean_incum', 'oat_env_mean_initial', 'mean_soy',
       'cognitive_dissonance_threshold', 'social_conformity',
       'count turtles with [color = yellow]', 'mean_almond',
       'oat_health_mean_initial', 'incumbent_initial_habit', 'habit_threshold',
       'p_interact', 'count turtles with [color = green]',
       'almond_health_mean_initial', 'mean_env_impact',
       'social_susceptibility', 'total_milk', 'network_parameter',
       'memory_lifetime', 'mean_health_impact', 'soy_env_mean_initial'],
      dtype='object')

In [75]:
from statsmodels.formula.api import mixedlm
from patsy import dmatrix

dependent_variables = ["mean_oat", "mean_almond", "mean_soy", "mean_incum"]

results = {}

for dep_var in dependent_variables:
   
    formula = f"Q('{dep_var}') ~ Q('[step]')"
    
  
    model = mixedlm(formula, grouped_data, groups=grouped_data["social_blindness"])
    result = model.fit(method='cg')  
    results[dep_var] = result.summary()


for dep_var, summary in results.items():
    print(f"Mixed Linear Model Results for {dep_var}:")
    print(summary)
    print("\n")

Mixed Linear Model Results for mean_oat:
           Mixed Linear Model Regression Results
===========================================================
Model:            MixedLM Dependent Variable: Q('mean_oat')
No. Observations: 73600   Method:             REML
No. Groups:       10      Scale:              8050.0182
Min. group size:  7360    Log-Likelihood:     -435417.8292
Max. group size:  7360    Converged:          Yes
Mean group size:  7360.0
-----------------------------------------------------------
               Coef.  Std.Err.   z    P>|z|  [0.025  0.975]
-----------------------------------------------------------
Intercept     360.520    4.679 77.047 0.000 351.349 369.691
Q('[step]')     1.059    0.025 42.514 0.000   1.010   1.108
Group Var     214.716    1.146
===========================================================



Mixed Linear Model Results for mean_almond:
            Mixed Linear Model Regression Results
==============================================================
Model:            MixedLM Dependent Variable: Q('mean_almond')
No. Observations: 73600   Method:             REML
No. Groups:       10      Scale:              7907.5840
Min. group size:  7360    Log-Likelihood:     -434760.1658
Max. group size:  7360    Converged:          Yes
Mean group size:  7360.0
---------------------------------------------------------------
              Coef.   Std.Err.    z     P>|z|   [0.025   0.975]
---------------------------------------------------------------
Intercept    359.798     4.284  83.989  0.000  351.402  368.194
Q('[step]')    0.596     0.025  24.142  0.000    0.548    0.644
Group Var    179.353     0.960
==============================================================



Mixed Linear Model Results for mean_soy:
           Mixed Linear Model Regression Results
===========================================================
Model:            MixedLM Dependent Variable: Q('mean_soy')
No. Observations: 73600   Method:             REML
No. Groups:       10      Scale:              7544.7017
Min. group size:  7360    Log-Likelihood:     -433039.4335
Max. group size:  7360    Converged:          Yes
Mean group size:  7360.0
-----------------------------------------------------------
             Coef.   Std.Err.    z    P>|z|  [0.025  0.975]
-----------------------------------------------------------
Intercept    349.143   10.068  34.680 0.000 329.410 368.875
Q('[step]')    2.765    0.024 114.648 0.000   2.718   2.812
Group Var   1009.601    5.467
===========================================================



Mixed Linear Model Results for mean_incum:
            Mixed Linear Model Regression Results
==============================================================
Model:             MixedLM Dependent Variable: Q('mean_incum')
No. Observations:  73600   Method:             REML
No. Groups:        10      Scale:              66693.5093
Min. group size:   7360    Log-Likelihood:     -513230.4649
Max. group size:   7360    Converged:          Yes
Mean group size:   7360.0
--------------------------------------------------------------
             Coef.   Std.Err.    z     P>|z|  [0.025   0.975]
--------------------------------------------------------------
Intercept   1360.208   20.025   67.925 0.000 1320.959 1399.456
Q('[step]')  -26.016    0.072 -362.824 0.000  -26.156  -25.875
Group Var   3974.939    7.268
==============================================================

In [76]:
from statsmodels.formula.api import mixedlm

# 定义包含交互项的模型公式
formula = "Q('mean_oat') ~ Q('[step]') + Q('social_blindness') + Q('[step]'):Q('social_blindness')"

# 拟合模型
model = mixedlm(formula, grouped_data, groups=grouped_data["[run number]"])
result = model.fit(method='cg')

# 输出结果
print(result.summary())

                      Mixed Linear Model Regression Results
=================================================================================
Model:                    MixedLM        Dependent Variable:        Q('mean_oat')
No. Observations:         73600          Method:                    REML
No. Groups:               1600           Scale:                     7615.2944
Min. group size:          46             Log-Likelihood:            -434350.1798
Max. group size:          46             Converged:                 Yes
Mean group size:          46.0
---------------------------------------------------------------------------------
                                   Coef.  Std.Err.    z    P>|z|  [0.025   0.975]
---------------------------------------------------------------------------------
Intercept                         414.976    1.753 236.689 0.000  411.539 418.412
Q('[step]')                        -0.574    0.052 -10.964 0.000   -0.676  -0.471
Q('social_blindness')             -99.011    2.826 -35.040 0.000 -104.549 -93.473
Q('[step]'):Q('social_blindness')   2.969    0.084  35.196 0.000    2.804   3.134
Group Var                         412.843    0.237
=================================================================================

## scale data

In [84]:
from sklearn.preprocessing import StandardScaler
from statsmodels.formula.api import mixedlm

# Step 1: 标准化数据
scaler = StandardScaler()
scaled_data = grouped_data.copy()
scaled_columns = ["[step]", "social_blindness"]
scaled_data[scaled_columns] = scaler.fit_transform(scaled_data[scaled_columns])

# Step 2: 定义模型并拟合
dependent_variables = ["mean_oat", "mean_almond", "mean_soy", "mean_incum"]
results = {}

for dep_var in dependent_variables:
    formula = f"Q('{dep_var}') ~ Q('[step]') + Q('social_blindness') + Q('[step]'):Q('social_blindness')"
    model = mixedlm(formula, scaled_data, groups=scaled_data["[run number]"])
    result = model.fit(method='cg')
    results[dep_var] = result.summary()

# Step 3: 打印结果
for dep_var, summary in results.items():
    print(f"Mixed Linear Model Results for {dep_var}:")
    print(summary)
    print("\n")

Mixed Linear Model Results for mean_oat:
                     Mixed Linear Model Regression Results
================================================================================
Model:                   MixedLM        Dependent Variable:        Q('mean_oat')
No. Observations:        73600          Method:                    REML
No. Groups:              1600           Scale:                     7615.2944
Min. group size:         46             Log-Likelihood:            -434347.5028
Max. group size:         46             Converged:                 Yes
Mean group size:         46.0
--------------------------------------------------------------------------------
                                   Coef.  Std.Err.    z    P>|z|  [0.025  0.975]
--------------------------------------------------------------------------------
Intercept                         384.349    0.601 639.255 0.000 383.171 385.527
Q('[step]')                        14.060    0.322  43.711 0.000  13.430  14.691
Q('social_blindness')              -9.251    0.601 -15.387 0.000 -10.430  -8.073
Q('[step]'):Q('social_blindness')  11.321    0.322  35.196 0.000  10.691  11.952
Group Var                         412.843    0.237
================================================================================



Mixed Linear Model Results for mean_almond:
                     Mixed Linear Model Regression Results
================================================================================
Model:                  MixedLM       Dependent Variable:       Q('mean_almond')
No. Observations:       73600         Method:                   REML
No. Groups:             1600          Scale:                    7483.0726
Min. group size:        46            Log-Likelihood:           -433644.4883
Max. group size:        46            Converged:                Yes
Mean group size:        46.0
--------------------------------------------------------------------------------
                                   Coef.  Std.Err.    z    P>|z|  [0.025  0.975]
--------------------------------------------------------------------------------
Intercept                         373.210    0.575 649.534 0.000 372.084 374.336
Q('[step]')                         7.913    0.319  24.818 0.000   7.288   8.538
Q('social_blindness')              -7.785    0.575 -13.550 0.000  -8.912  -6.659
Q('[step]'):Q('social_blindness')  12.639    0.319  39.639 0.000  12.014  13.264
Group Var                         365.554    0.218
================================================================================



Mixed Linear Model Results for mean_soy:
                     Mixed Linear Model Regression Results
================================================================================
Model:                   MixedLM        Dependent Variable:        Q('mean_soy')
No. Observations:        73600          Method:                    REML
No. Groups:              1600           Scale:                     6945.3525
Min. group size:         46             Log-Likelihood:            -431298.2238
Max. group size:         46             Converged:                 Yes
Mean group size:         46.0
--------------------------------------------------------------------------------
                                   Coef.  Std.Err.    z    P>|z|  [0.025  0.975]
--------------------------------------------------------------------------------
Intercept                         411.354    0.710 579.359 0.000 409.962 412.745
Q('[step]')                        36.707    0.307 119.493 0.000  36.105  37.309
Q('social_blindness')             -28.880    0.710 -40.675 0.000 -30.272 -27.489
Q('[step]'):Q('social_blindness')  -4.726    0.307 -15.385 0.000  -5.328  -4.124
Group Var                         655.608    0.346
================================================================================



Mixed Linear Model Results for mean_incum:
                       Mixed Linear Model Regression Results
====================================================================================
Model:                     MixedLM        Dependent Variable:        Q('mean_incum')
No. Observations:          73600          Method:                    REML
No. Groups:                1600           Scale:                     58865.5960
Min. group size:           46             Log-Likelihood:            -510283.5086
Max. group size:           46             Converged:                 Yes
Mean group size:           46.0
------------------------------------------------------------------------------------
                                   Coef.   Std.Err.    z     P>|z|  [0.025   0.975]
------------------------------------------------------------------------------------
Intercept                          774.855    2.559  302.792 0.000  769.840  779.871
Q('[step]')                       -345.382    0.894 -386.196 0.000 -347.135 -343.629
Q('social_blindness')               41.528    2.559   16.228 0.000   36.512   46.543
Q('[step]'):Q('social_blindness')  -22.312    0.894  -24.948 0.000  -24.065  -20.559
Group Var                         9198.173    1.545
====================================================================================